Apa style
TeachBooks/manual pull request #38
Opened 2024-12-05 09:55 UTC by rlanzafame

Note that this should be considered a stable but temporary fix; this should be done with a sphinx extension. See project description https://github.com/orgs/TeachBooks/projects/17/views/1

2024-12-05 10:12 UTC, Tom-van-Woudenberg approved these changes

2024-12-05 10:59 UTC, Tom-van-Woudenberg requested changes
Built gives error:
```
/home/runner/work/manual/manual/book/_ext/pybtexapastyle/labels/apa.py:59: SyntaxWarning: is with a literal. Did you mean ==?
  if len(persons) is 1:
/home/runner/work/manual/manual/book/_ext/pybtexapastyle/labels/apa.py:61: SyntaxWarning: is with a literal. Did you mean ==?
  elif len(persons) is 2:
  ```

2024-12-06 08:12 UTC, rlanzafame commented
psssssh it's a warning, not an error!

2024-12-06 08:51 UTC, rlanzafame commented
@Tom-van-Woudenberg i think its foine now

2024-12-06 12:31 UTC, merged